version: 2
jobs:
    website:
      working_directory: ~/website
      docker:
        - image: circleci/node
      steps:
        - checkout
        - run:
            name: install node packages
            command: yarn install
        - run:
            name: authenticate bot
            command: ./dev/gitbot.sh
        - run:
            name: publish site
            command: ./dev/publish.sh
    flake8:
      working_directory: ~/bench
      docker:
        - image: python:3.6.3
      steps:
        - checkout
        - run:
            command: pip install -r dev/requirements/ci.txt
        - run:
            command: flake8
    benchmark:
      working_directory: ~/bench
      machine: true
      steps:
        - checkout
        - run:
            command: make build
        - run:
            name: information about benchmarks
            command: ./benchmark.sh --info
        - run:
            name: run benchmarks
            command: ./benchmark.sh -J results/benchmarks.json
        - run:
            name: upload to S3
            command: python -m benchmarks.upload results/benchmarks.json --path $BENCHMARK_PATH
        - run:
            name: dockerhub login
            command: docker login -p $DOCKER_PASS -e $DOCKER_EMAIL -u $DOCKER_USER
        - run:
            command: make push


workflows:
  version: 2
  build-n-deploy:
    jobs:
      - flake8:
          filters:
            branches:
              only: master
      - website:
          filters:
            branches:
              only: master
      - benchmark:
          filters:
            branches:
              only: benchmark
